### PR TITLE
Fix typo in add.py. Closes #7

### LINKED ISSUE #7: Fix typo in add.py
Change provide->provides in the docstring

### PR DESCRIPTION
**Pull request by iakat**
:tada:

### CODE REVIEW

**Comment by sims1253** [comment]
The fix looks fine but the commit message needs a touch. Could you take a look at our guidelines and rework acordingly?
http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

Thank you! 

By the way, to edit the last commit, use git commit --amend, edit it, save it, and then push again with the extra flag --force :)

**Comment by iakat** [comment]
Can you check it now?

**Comment by sims1253** [comment]
ack bca8658

**Comment by iakat** [comment]
Changed `Fixes` to `Closes` following Gitter conversation about typos being `Closes`.

**Comment by sils** [comment]
reack https://github.com/coala-analyzer/coala-tutorial/pull/8/commits/d5b00fd6e9b81179bfcd4547a3f1d5b04a192524

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
