### PR TITLE
Update the bears to match with the examples in the native bears tutorial

### PR DESCRIPTION
**Pull request by Kagamihime**
Closes https://github.com/coala/coala-tutorial/issues/10

### CODE REVIEW

**Review by newbazz — CHANGES_REQUESTED** [review]
Squash your commits

**Comment by Kagamihime** [comment]
@newbazz Each commit describe a change made in different files, otherwise the commits wouldn't be atomic.

**Comment by Kagamihime** [comment]
@Makman2 Could you review it, please? It's been a while

**Comment by Makman2** [comment]
Two possibilities:
1. Split up the issue into two issues for each file you are modifying. Two issues can't close a single issue :)
2. Squash the commits.

Latter is probably easier ;) And it's actually okay in this case, you are modifying many files in one commit then, but for the same purpose :+1: Up to you :)

**Comment by Makman2** [comment]
Looks good otherwise ;)

**Comment by Kagamihime** [comment]
@Makman2 I've done the changes!

**Review by li-boxuan — APPROVED** [review]

**Comment by Makman2** [comment]
ack 20bec32d34eaaabb6f933b8d1b9c39b34e8fdbce

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
